### ISSUE TITLE
Vegas Rules, can't select 1 card or 3 card draw

### ISSUE THREAD

**Issue by francoisvandette** [roymw09/solitaire-libgdx#37]
If either "1 Card Draw" or "3 Card Draw" are selected, I can not start a Vegas Rules game.

A Vegas style game will start if neither "1 Card Draw" nor "3 Card Draw" are selected.

**Comment by MichaelThomas0721** [comment]
I think vegas rules are only draw 1 in the rules, I'm not sure though
